# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a87a639d4a894dca125c4af23ab33f58c8bd26e3bce5954bebcdf0e543fa20ca0d168956dcaddba2f7504e0290f4bdf3ca78ab523c14b76c5f7c4d8277c0c4ce

test:
  secret_key_base: 160da6327429dd3d8ca5539df25bfab76ed091d9d4d688a32d2d07f271dfddfb0bbc18bb69ed4f81a51b875249e8f9ad64bb3f2a898262d57d5a9afc72b21f79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
